# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='audit_log',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='log_time',
        ),
    ]
