# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
