# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-16 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20170816_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='host_user_binds',
        ),
    ]
