# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionlog',
            name='account',
        ),
        migrations.RemoveField(
            model_name='sessionlog',
            name='host_user_bind',
        ),
        migrations.DeleteModel(
            name='SessionLog',
        ),
    ]
